name: dart_merkle_lib
description: A performance conscious package for merkle root and tree calculations.
version: 1.0.0
homepage: https://github.com/dart-bitcoin-lib/dart-merkle-lib
repository: https://github.com/dart-bitcoin-lib/dart-merkle-lib
issue_tracker: https://github.com/dart-bitcoin-lib/dart-merkle-lib/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  crypto: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0
  convert: ^3.0.1
